<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { resolveMediaUrl } from '@/utils/media';
import imageWidths from '@/data/image-widths.json';

interface Props {
  src?: string | null;
  alt: string;
  aspectRatio?: string;
  objectFit?: 'cover' | 'contain';
  eager?: boolean;
  /** Card thumbnails only — see the trimmed-derivative note below. */
  preferTrimmed?: boolean;
  /**
   * The `sizes` hint that goes with the generated `srcset`. Without it the
   * browser assumes the image fills the viewport and picks the widest file,
   * which throws the whole point away — so pass the width the layout actually
   * gives this image. Ignored for sources that have no variants.
   */
  sizes?: string;
}

const props = withDefaults(defineProps<Props>(), {
  src: '',
  aspectRatio: undefined,
  objectFit: 'cover',
  eager: false,
  preferTrimmed: false,
  sizes: undefined,
});

const loaded = ref(false);
const errored = ref(false);
/** Index into `candidates` of the URL currently being attempted. */
const candidateIndex = ref(0);

const JPG_PNG = /^\/(images|uploads\/images)\/.+\.(jpe?g|png)$/i;

/**
 * Ordered fallback chain, tried in turn via onError so a missing derivative
 * costs one failed request rather than a broken image.
 *
 * When `preferTrimmed` is set (product-grid card thumbnails), a
 * background-removed "<name>_trim" derivative is tried first — real ML
 * segmentation (scripts/remove-product-bg.py, rembg/u2net), not a white-pixel
 * threshold, so it also works on the handful of dark editorial/lifestyle
 * shots. Source photography carries wildly inconsistent amounts of margin
 * baked into the file (some shots ~60% empty space, others ~95% watch),
 * which made cards look randomly different in scale even in identical
 * containers; the derivative is cropped to the watch's actual content box
 * (plus a little breathing room) so it reads at a consistent size everywhere,
 * and — since it's true alpha transparency rather than a baked-in white
 * background — shows correctly in both the light and dark theme. Only .webp
 * and .png carry alpha (a JPEG can't), so this chain always ends on the
 * untouched original JPEG, which is guaranteed to exist.
 */
const candidates = computed(() => {
  const src = props.src ?? '';
  const isJpgPng = JPG_PNG.test(src);
  const list: string[] = [];

  if (props.preferTrimmed && isJpgPng) {
    const trimBase = src.replace(/\.(jpe?g|png)$/i, '_trim');
    list.push(resolveMediaUrl(`${trimBase}.webp`));
    list.push(resolveMediaUrl(`${trimBase}.png`));
  }
  // Everything under /public/images, plus the product photography in
  // backend/uploads/images, ships with a WebP sibling (roughly an eighth of
  // the JPEG's weight).
  if (isJpgPng) {
    list.push(resolveMediaUrl(src.replace(/\.(jpe?g|png)$/i, '.webp')));
  }
  list.push(resolveMediaUrl(src));
  return list;
});

const displaySrc = computed(() => candidates.value[candidateIndex.value] ?? '');

/**
 * Width variants for the editorial photography, generated by
 * scripts/responsive-images.mjs. Only sources listed in the manifest get a
 * `srcset`: unlike the candidate chain above, a srcset entry that 404s gives a
 * broken image rather than falling back, so guessing is not an option. Product
 * photography is served from the API host and has no variants, so it keeps the
 * single-source path.
 */
/**
 * Product photography is resized by the API on request
 * (backend/src/middleware/resizeImages.ts), so unlike the editorial set it
 * needs no manifest — every allowed width of an existing file resolves, and a
 * file that does not exist was already broken at its base URL. These have to
 * match ALLOWED_WIDTHS on the server; anything else falls through to the
 * full-size original.
 */
const UPLOAD_WIDTHS = [240, 480, 720, 960, 1440];

const srcset = computed(() => {
  const src = displaySrc.value;
  if (!src) return undefined;

  if (src.includes('/uploads/images/')) {
    return UPLOAD_WIDTHS.map((w) => `${src}?w=${w} ${w}w`).join(', ');
  }

  const widths = imageWidths[src as keyof typeof imageWidths] as number[] | undefined;
  if (!widths?.length) return undefined;
  const stem = src.replace(/\.webp$/, '');
  const max = Math.max(...widths);
  return widths.map((w) => (w === max ? `${src} ${w}w` : `${stem}-${w}.webp ${w}w`)).join(', ');
});

watch(
  () => [props.src, props.preferTrimmed],
  () => {
    loaded.value = false;
    errored.value = false;
    candidateIndex.value = 0;
  },
);

function onLoad() {
  loaded.value = true;
}

function onError() {
  if (candidateIndex.value < candidates.value.length - 1) {
    candidateIndex.value += 1;
    return;
  }
  errored.value = true;
}
</script>

<template>
  <div class="sw-smart-image" :style="aspectRatio ? { aspectRatio } : undefined">
    <div class="sw-smart-image__placeholder" :class="{ 'is-hidden': loaded }" />
    <img
      v-if="displaySrc && !errored"
      :key="displaySrc"
      :src="displaySrc"
      :srcset="srcset"
      :sizes="srcset ? (sizes ?? '100vw') : undefined"
      :alt="alt"
      :loading="eager ? 'eager' : 'lazy'"
      :decoding="eager ? 'sync' : 'async'"
      :fetchpriority="eager ? 'high' : 'auto'"
      class="sw-smart-image__img"
      :class="{ 'is-loaded': loaded }"
      :style="{ objectFit }"
      @load="onLoad"
      @error="onError"
    />
    <div v-else class="sw-smart-image__fallback" aria-hidden="true" />
  </div>
</template>

<style scoped>
.sw-smart-image {
  position: relative;
  overflow: hidden;
  width: 100%;
  height: 100%;
  background: var(--surface-media);
}

.sw-smart-image__placeholder {
  position: absolute;
  inset: 0;
  background: linear-gradient(120deg, var(--surface-media) 0%, var(--surface-media-hi) 50%, var(--surface-media) 100%);
  background-size: 200% 100%;
  animation: sw-shimmer 1.8s ease-in-out infinite;
  transition: opacity var(--dur-mid) var(--ease-luxury);
}

.sw-smart-image__placeholder.is-hidden {
  opacity: 0;
  pointer-events: none;
}

.sw-smart-image__img {
  width: 100%;
  height: 100%;
  opacity: 0;
  transform: scale(1.03);
  transition: opacity var(--dur-slow) var(--ease-luxury), transform 1.4s var(--ease-luxury);
}

.sw-smart-image__img.is-loaded {
  opacity: 1;
  transform: scale(1);
}

.sw-smart-image__fallback {
  position: absolute;
  inset: 0;
  background: var(--surface-media);
}

@keyframes sw-shimmer {
  0% {
    background-position: 200% 0;
  }
  100% {
    background-position: -200% 0;
  }
}

@media (prefers-reduced-motion: reduce) {
  .sw-smart-image__img {
    transition: opacity var(--dur-fast) linear;
    transform: none;
  }
}
</style>
