import { Request, Response } from 'express';
import { AnalyticsEvent, EVENT_TYPES, EventType } from '../models/AnalyticsEvent';
import { AnalyticsSession } from '../models/AnalyticsSession';
import { readVisitorContext } from '../utils/visitorContext';
import { resolveChannel } from '../utils/channel';
import { env } from '../config/env';

/**
 * The one public, unauthenticated write in this API.
 *
 * Because anyone on the internet can post here, nothing in the body is
 * believed on its own: ids must look like ids, event types must be on the
 * allowlist, paths are truncated, timestamps far from now are replaced, and
 * the batch is capped. Everything that could identify a person — the IP
 * address, the User-Agent — is read from the request itself, used to derive a
 * country and a device class, and then dropped. The visitor id is a random
 * value the browser made up about itself, which is what keeps this cookieless.
 *
 * It always answers 204. A tracker that returns errors invites a storefront
 * that reacts to them, and no visitor's experience should depend on whether
 * analytics accepted a beacon.
 */

/** A batch is a page's worth of activity, not a bulk import. */
const MAX_EVENTS = 30;
const MAX_PATH = 300;
const MAX_REFERRER = 500;
const MAX_UTM = 120;
/** Ids are generated by `crypto.randomUUID()` in the browser. */
const ID_PATTERN = /^[a-zA-Z0-9_-]{8,64}$/;
/** A new session starts once a visitor has been idle this long. */
const SESSION_IDLE_MS = 30 * 60_000;

interface IncomingEvent {
  type?: unknown;
  path?: unknown;
  productSlug?: unknown;
  ts?: unknown;
}

function clean(value: unknown, max: number): string {
  return typeof value === 'string' ? value.trim().slice(0, max) : '';
}

/**
 * Keeps only the path, dropping the origin and the query string.
 *
 * A query string is where personal data ends up by accident — a search term,
 * an email in a link someone shared. The dashboard ranks pages, so the path
 * is the whole of what it needs.
 */
function cleanPath(value: unknown): string {
  const raw = clean(value, MAX_PATH);
  if (!raw) return '';
  const path = raw.startsWith('http') ? safePathname(raw) : raw;
  return (path.split('?')[0].split('#')[0] || '/').slice(0, MAX_PATH);
}

function safePathname(url: string): string {
  try {
    return new URL(url).pathname;
  } catch {
    return '';
  }
}

/** Clock skew and replayed batches both land outside this window. */
function cleanTimestamp(value: unknown): Date {
  const now = Date.now();
  const parsed = typeof value === 'number' ? value : Date.parse(String(value ?? ''));
  if (!Number.isFinite(parsed)) return new Date(now);
  const drift = Math.abs(now - parsed);
  return drift > 6 * 60 * 60_000 ? new Date(now) : new Date(parsed);
}

export async function track(req: Request, res: Response) {
  // Answered before any work: the storefront is never kept waiting on this,
  // and a failure below is ours to log, not the visitor's to see.
  res.status(204).end();

  try {
    await record(req);
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error('[analytics] failed to record a batch', err);
  }
}

async function record(req: Request) {
  const context = readVisitorContext(req);
  // Crawlers and monitors are not visitors. Dropped here so they never reach
  // the collections, rather than being filtered out of every later query.
  if (context.isBot) return;

  const body = req.body as Record<string, unknown>;
  const visitorId = clean(body.visitorId, 64);
  const sessionId = clean(body.sessionId, 64);
  if (!ID_PATTERN.test(visitorId) || !ID_PATTERN.test(sessionId)) return;

  const rawEvents = Array.isArray(body.events) ? (body.events as IncomingEvent[]) : [];
  const events = rawEvents
    .slice(0, MAX_EVENTS)
    .map((event) => ({
      type: clean(event.type, 40) as EventType,
      path: cleanPath(event.path),
      productSlug: clean(event.productSlug, 120) || undefined,
      ts: cleanTimestamp(event.ts),
    }))
    .filter((event) => (EVENT_TYPES as readonly string[]).includes(event.type));

  if (!events.length) return;

  const pageviews = events.filter((event) => event.type === 'pageview');
  const now = new Date();

  await Promise.all([
    upsertSession({ visitorId, sessionId, pageviews, context, body, now }),
    AnalyticsEvent.insertMany(
      events.map((event) => ({ ...event, visitorId, sessionId })),
      // One malformed row must not discard the rest of the batch.
      { ordered: false },
    ),
  ]);
}

interface UpsertArgs {
  visitorId: string;
  sessionId: string;
  pageviews: { path: string; ts: Date }[];
  context: ReturnType<typeof readVisitorContext>;
  body: Record<string, unknown>;
  now: Date;
}

/**
 * Creates the session on its first batch and advances it on every later one.
 *
 * The split matters: entry page, referrer, channel and device belong to the
 * moment the visit began and must never be overwritten by a later batch
 * (`$setOnInsert`), while the last-seen time, the exit page and the page count
 * are the current state of the visit (`$set` / `$inc`).
 */
async function upsertSession({ visitorId, sessionId, pageviews, context, body, now }: UpsertArgs) {
  const referrer = clean(body.referrer, MAX_REFERRER);
  const utmSource = clean(body.utmSource, MAX_UTM) || undefined;
  const entryPath = cleanPath(body.entryPath) || pageviews[0]?.path || '';
  const exitPath = pageviews.at(-1)?.path;

  const existing = await AnalyticsSession.exists({ sessionId });

  if (!existing) {
    // A visitor with an earlier session is a returning one. Resolved once per
    // session rather than per event — it is an indexed existence check, and
    // asking it on every pageview would be the query this collection is
    // hammered by.
    const seenBefore = await AnalyticsSession.exists({ visitorId });

    try {
      await insertSession(seenBefore);
    } catch (err) {
      // Two batches for a brand-new session can both find no row and both try
      // to create it; the unique index on sessionId lets exactly one win. The
      // loser is not an error — the session exists now, so fall through and
      // advance it, which is what it was going to do anyway.
      if (!isDuplicateKey(err)) throw err;
      await advanceSession();
    }
    return;
  }

  await advanceSession();

  function insertSession(seenBefore: unknown) {
    return AnalyticsSession.updateOne(
      { sessionId },
      {
        $setOnInsert: {
          visitorId,
          sessionId,
          startedAt: now,
          entryPath,
          referrer,
          channel: resolveChannel(referrer, utmSource, env.siteHost),
          utmSource,
          utmMedium: clean(body.utmMedium, MAX_UTM) || undefined,
          utmCampaign: clean(body.utmCampaign, MAX_UTM) || undefined,
          country: context.country,
          city: context.city,
          device: context.device,
          browser: context.browser,
          os: context.os,
          isNewVisitor: !seenBefore,
        },
        $set: { lastSeenAt: now, ...(exitPath ? { exitPath } : {}) },
        $inc: { pageviews: pageviews.length },
      },
      { upsert: true },
    );
  }

  function advanceSession() {
    return AnalyticsSession.updateOne(
      { sessionId },
      {
        $set: { lastSeenAt: now, ...(exitPath ? { exitPath } : {}) },
        $inc: { pageviews: pageviews.length },
      },
    );
  }
}

function isDuplicateKey(err: unknown): boolean {
  return Boolean(err && typeof err === 'object' && (err as { code?: number }).code === 11000);
}

/** Exported for the session-expiry rule the storefront applies client-side. */
export const SESSION_IDLE_LIMIT_MS = SESSION_IDLE_MS;
